baseURL = 'http://se-tutorship.ru'
languageCode = 'ru-ru'
title = 'Курс молодого ПИшника'
theme = 'stack'
buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
